<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T04_wsheet_model extends CI_Model
{

    public $table = 't04_wsheet';
    public $id = 'idwsheet';
    public $order = 'ASC';
    public $join = 't03_mapel';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->select($this->table.'.*');
        $this->db->select($this->join.'.MataPelajaran');
        $this->db->from($this->table);
        $this->db->join($this->join, $this->join . '.idmapel = ' . $this->table . '.idmapel', 'left');
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        $this->db->select($this->table.'.*');
        $this->db->select($this->join.'.MataPelajaran');
        $this->db->from($this->table);
        $this->db->join($this->join, $this->join . '.idmapel = ' . $this->table . '.idmapel', 'left');
        return $this->db->get()->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like($this->join . '.MataPelajaran', $q);
		$this->db->or_like('Kdasar', $q);
        $this->db->select($this->table.'.*');
        $this->db->select($this->join.'.MataPelajaran');
        $this->db->from($this->table);
        $this->db->join($this->join, $this->join . '.idmapel = ' . $this->table . '.idmapel', 'left');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        // $this->db->order_by($this->id, $this->order);
        $this->db->order_by('urut', $this->order);
        $this->db->like($this->join . '.MataPelajaran', $q);
		$this->db->or_like('Kdasar', $q);
		$this->db->limit($limit, $start);
        $this->db->select($this->table.'.*');
        $this->db->select($this->join.'.MataPelajaran');
        $this->db->from($this->table);
        $this->db->join($this->join, $this->join . '.idmapel = ' . $this->table . '.idmapel', 'left');
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    /**
     * ambil data sub kompetensi dasar (level terakhir)
     */
    function getDataLastLevel()
    {
        $this->db->where('induk <> \'0\'');
        $this->db->order_by('urut', 'asc');
        return $this->db->get($this->table)->result();
    }

    /**
     * ambil data sub kompetensi dasar (level terakhir) berdasarkan idwsheet
     */
    function getData($idwsheet)
    {
        $this->db->where('induk', $idwsheet);
        return $this->db->get($this->table)->result();
    }

}

/* End of file T04_wsheet_model.php */
/* Location: ./application/models/T04_wsheet_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-04-26 14:21:17 */
/* http://harviacode.com */
