<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T30_absensi_model extends CI_Model
{

    public $table = 't30_absensi';
    public $id = 'idabsensi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idabsensi', $q);
		$this->db->or_like('idsiswa', $q);
		$this->db->or_like('S', $q);
		$this->db->or_like('I', $q);
		$this->db->or_like('A', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idabsensi', $q);
		$this->db->or_like('idsiswa', $q);
		$this->db->or_like('S', $q);
		$this->db->or_like('I', $q);
		$this->db->or_like('A', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T30_absensi_model.php */
/* Location: ./application/models/T30_absensi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-04-24 23:08:52 */
/* http://harviacode.com */