<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T31_talent_model extends CI_Model
{

    public $table = 't31_talent';
    public $id = 'idtalenttr';
    public $order = 'ASC';
    public $join = 't00_siswa';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->select($this->table.'.*');
        $this->db->select($this->join.'.Nama');
        $this->db->from($this->table);
        $this->db->join($this->join, $this->join . '.idsiswa = ' . $this->table . '.idsiswa', 'left');
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        $this->db->select($this->table.'.*');
        $this->db->select($this->join.'.Nama');
        $this->db->from($this->table);
        $this->db->join($this->join, $this->join . '.idsiswa = ' . $this->table . '.idsiswa', 'left');
        return $this->db->get()->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like($this->join . '.Nama', $q);
		$this->db->or_like('TalentNilai', $q);
        $this->db->select($this->table.'.*');
        $this->db->select($this->join.'.Nama');
        $this->db->from($this->table);
        $this->db->join($this->join, $this->join . '.idsiswa = ' . $this->table . '.idsiswa', 'left');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like($this->join . '.Nama', $q);
		$this->db->or_like('TalentNilai', $q);
		$this->db->limit($limit, $start);
        $this->db->select($this->table.'.*');
        $this->db->select($this->join.'.Nama');
        $this->db->from($this->table);
        $this->db->join($this->join, $this->join . '.idsiswa = ' . $this->table . '.idsiswa', 'left');
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T31_talent_model.php */
/* Location: ./application/models/T31_talent_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-04-25 02:47:28 */
/* http://harviacode.com */
